CREATE TABLE ACL (
	AclTournament INT NOT NULL,
	AclIP VARCHAR(15) NOT NULL,
	AclNick VARCHAR(50) NOT NULL,
	AclEnabled TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB;
ALTER TABLE ACL ADD CONSTRAINT PK_ACL PRIMARY KEY(AclIP,AclTournament);
CREATE TABLE Entries (
	EnId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	EnOnlineId INT NOT NULL DEFAULT 0,
	EnTournament INT UNSIGNED NOT NULL DEFAULT 0,
	EnDivision VARCHAR(2) NOT NULL,
	EnClass VARCHAR(2) NOT NULL,
	EnSubClass VARCHAR(2) NOT NULL,
	EnAgeClass VARCHAR(2) NOT NULL,
	EnCountry INT UNSIGNED NOT NULL DEFAULT 0,
	EnIocCode VARCHAR(5) NOT NULL DEFAULT '',
	EnSubTeam TINYINT NOT NULL DEFAULT 0,
	EnCountry2 INT UNSIGNED NOT NULL DEFAULT 0,
	EnCountry3 INT UNSIGNED NOT NULL DEFAULT 0,
	EnCtrlCode VARCHAR(16) NOT NULL,
	EnDob DATE NOT NULL,
	EnCode VARCHAR(25) NOT NULL,
	EnName VARCHAR(30) NOT NULL,
	EnFirstName VARCHAR(30) NOT NULL,
	EnBadgePrinted DATETIME DEFAULT NULL,
	EnAthlete BIT(3) NOT NULL DEFAULT 49,
	EnSex BIT(3) NOT NULL DEFAULT 48,
	EnWChair BIT(3) NOT NULL DEFAULT 48,
	EnSitting BIT(3) NOT NULL DEFAULT 48,
	EnIndClEvent BIT(3) NOT NULL DEFAULT 49,
	EnTeamClEvent BIT(3) NOT NULL DEFAULT 49,
	EnIndFEvent BIT(3) NOT NULL DEFAULT 49,
	EnTeamFEvent BIT(3) NOT NULL DEFAULT 49,
	EnTeamMixEvent BIT(3) NOT NULL DEFAULT 49,
	EnDoubleSpace BIT(3) NOT NULL DEFAULT 48,
	EnPays BIT(3) NOT NULL DEFAULT 49,
	EnStatus TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EnTargetFace INT NOT NULL,
	EnLueTimeStamp DATETIME NOT NULL,
	EnLueFieldChanged SMALLINT NOT NULL,
	EnTimestamp TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	EnNameOrder TINYINT NOT NULL
) ENGINE=InnoDB;
CREATE INDEX CalcRank ON Entries (EnTournament,EnAthlete,EnStatus);
CREATE INDEX EnClass ON Entries (EnClass);
CREATE INDEX EnCode ON Entries (EnCode,EnIocCode,EnDivision,EnTournament);
CREATE INDEX EnDivision ON Entries (EnDivision);
CREATE INDEX EnTournament ON Entries (EnTournament);
CREATE TABLE InvolvedType (
	ItId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ItDescription VARCHAR(32) NOT NULL,
	ItJudge TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ItDoS TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ItJury TINYINT UNSIGNED NOT NULL,
	ItOC TINYINT UNSIGNED NOT NULL
) ENGINE=InnoDB;
CREATE TABLE TeamComponent (
	TcCoId INT NOT NULL,
	TcSubTeam TINYINT NOT NULL,
	TcTournament INT NOT NULL,
	TcEvent VARCHAR(4) NOT NULL,
	TcId INT UNSIGNED NOT NULL,
	TcFinEvent TINYINT UNSIGNED NOT NULL DEFAULT 0,
	TcOrder TINYINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE TeamComponent ADD CONSTRAINT PK_TeamComponent PRIMARY KEY(TcCoId,TcEvent,TcFinEvent,TcId,TcSubTeam,TcTournament);
CREATE TABLE Countries (
	CoId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CoOnlineId INT NOT NULL DEFAULT 0,
	CoTournament INT NOT NULL DEFAULT 0,
	CoIocCode VARCHAR(5) NOT NULL,
	CoCode VARCHAR(10) NOT NULL,
	CoName VARCHAR(30) NOT NULL,
	CoNameComplete VARCHAR(80) NOT NULL,
	CoSubCountry VARCHAR(10) NOT NULL,
	CoParent1 INT UNSIGNED NOT NULL,
	CoParent2 INT UNSIGNED NOT NULL
) ENGINE=InnoDB;
CREATE UNIQUE INDEX CoTournament ON Countries (CoTournament,CoCode);
CREATE TABLE FinWarmup (
	FwTournament INT NOT NULL,
	FwEvent VARCHAR(4) NOT NULL,
	FwTeamEvent INT NOT NULL,
	FwDay DATE NOT NULL,
	FwTime TIME NOT NULL,
	FwDuration INT NOT NULL,
	FwMatchTime TIME NOT NULL,
	FwTargets TEXT NOT NULL,
	FwOptions TEXT NOT NULL,
	FwTimestamp TIMESTAMP NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB;
ALTER TABLE FinWarmup ADD CONSTRAINT PK_FinWarmup PRIMARY KEY(FwDay,FwEvent,FwMatchTime,FwTeamEvent,FwTime,FwTournament);
CREATE TABLE RecTournament (
	RtTournament INT NOT NULL,
	RtRecType VARCHAR(2) NOT NULL,
	RtRecCode VARCHAR(25) NOT NULL,
	RtRecTeam SMALLINT NOT NULL,
	RtRecPara VARCHAR(1) NOT NULL,
	RtRecCategory VARCHAR(8) NOT NULL,
	RtRecDistance VARCHAR(50) NOT NULL,
	RtRecTotal SMALLINT NOT NULL,
	RtRecXNine SMALLINT NOT NULL,
	RtRecDate DATE NOT NULL,
	RtRecExtra TEXT NOT NULL,
	RtRecLastUpdated DATETIME NOT NULL,
	RtRecPhase TINYINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE RecTournament ADD CONSTRAINT PK_RecTournament PRIMARY KEY(RtRecCategory,RtRecCode,RtRecDistance,RtRecPara,RtRecTeam,RtRecType,RtTournament);
CREATE INDEX RtRecPhase ON RecTournament (RtTournament,RtRecType,RtRecCode,RtRecTeam,RtRecCategory,RtRecPhase);
CREATE TABLE iub_users (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) DEFAULT 'NULL',
	email VARCHAR(255) DEFAULT 'NULL',
	password_digest VARCHAR(255) DEFAULT 'NULL',
	enabled BIT(3) DEFAULT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
) ENGINE=InnoDB;
CREATE TABLE AvailableTarget (
	AtTournament INT UNSIGNED NOT NULL,
	AtTargetNo VARCHAR(5) NOT NULL,
	AtSession TINYINT UNSIGNED NOT NULL,
	AtTarget INT NOT NULL,
	AtLetter VARCHAR(1) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE AvailableTarget ADD CONSTRAINT PK_AvailableTarget PRIMARY KEY(AtTargetNo,AtTournament);
CREATE INDEX AtTournament ON AvailableTarget (AtTournament,AtSession,AtTarget,AtLetter);
CREATE TABLE TVOut (
	TVOId TINYINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TVOName VARCHAR(50) NOT NULL,
	TVOUrl TEXT NOT NULL,
	TVOMessage TEXT NOT NULL,
	TVORuleId INT NOT NULL,
	TVOTourCode VARCHAR(8) NOT NULL,
	TVORuleType TINYINT NOT NULL,
	TVOLastUpdate DATETIME NOT NULL
) ENGINE=InnoDB;
CREATE TABLE Flags (
	FlTournament INT NOT NULL DEFAULT 0,
	FlIocCode VARCHAR(5) NOT NULL,
	FlCode VARCHAR(10) NOT NULL,
	FlSVG MEDIUMBLOB NOT NULL DEFAULT '',
	FlJPG MEDIUMBLOB NOT NULL,
	FlEntered TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	FlChecked VARCHAR(1) NOT NULL DEFAULT '',
	FlContAssoc VARCHAR(10) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Flags ADD CONSTRAINT PK_Flags PRIMARY KEY(FlCode,FlIocCode,FlTournament);
CREATE INDEX FlEntered ON Flags (FlEntered);
CREATE TABLE IskData (
	IskDtTournament INT NOT NULL,
	IskDtMatchNo INT NOT NULL,
	IskDtEvent VARCHAR(4) NOT NULL,
	IskDtTeamInd INT NOT NULL,
	IskDtType VARCHAR(2) NOT NULL,
	IskDtTargetNo VARCHAR(5) NOT NULL,
	IskDtDistance INT NOT NULL,
	IskDtEndNo INT NOT NULL,
	IskDtArrowstring VARCHAR(9) NOT NULL,
	IskDtUpdate DATETIME NOT NULL,
	IskDtDevice VARCHAR(36) NOT NULL,
	IskDtSession TINYINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE IskData ADD CONSTRAINT PK_IskData PRIMARY KEY(IskDtDistance,IskDtEndNo,IskDtEvent,IskDtMatchNo,IskDtSession,IskDtTargetNo,IskDtTeamInd,IskDtTournament,IskDtType);
CREATE TABLE VxA (
	VxAId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	VxAValue VARCHAR(5) NOT NULL,
	VxATeam BIT(3) NOT NULL DEFAULT 48
) ENGINE=InnoDB;
CREATE TABLE FinalReportA (
	FraQuestion VARCHAR(5) NOT NULL,
	FraTournament INT UNSIGNED NOT NULL,
	FraAnswer TEXT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE FinalReportA ADD CONSTRAINT PK_FinalReportA PRIMARY KEY(FraQuestion,FraTournament);
CREATE TABLE Divisions (
	DivId VARCHAR(2) NOT NULL,
	DivTournament INT UNSIGNED NOT NULL DEFAULT 0,
	DivDescription VARCHAR(32) NOT NULL,
	DivViewOrder TINYINT UNSIGNED NOT NULL DEFAULT 0,
	DivAthlete VARCHAR(1) NOT NULL DEFAULT '1',
	DivRecDivision VARCHAR(4) NOT NULL,
	DivWaDivision VARCHAR(4) NOT NULL,
	DivTourRules VARCHAR(75) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Divisions ADD CONSTRAINT PK_Divisions PRIMARY KEY(DivId,DivTournament);
CREATE INDEX DivTournament ON Divisions (DivTournament,DivAthlete,DivViewOrder);
CREATE TABLE TVRules (
	TVRId INT NOT NULL,
	TVRTournament INT NOT NULL,
	TVRName VARCHAR(50) NOT NULL,
	TV_TR_BGColor VARCHAR(7) NOT NULL,
	TV_TRNext_BGColor VARCHAR(7) NOT NULL,
	TV_TR_Color VARCHAR(7) NOT NULL,
	TV_TRNext_Color VARCHAR(7) NOT NULL,
	TV_Content_BGColor VARCHAR(7) NOT NULL,
	TV_Page_BGColor VARCHAR(7) NOT NULL,
	TV_TH_BGColor VARCHAR(7) NOT NULL,
	TV_TH_Color VARCHAR(7) NOT NULL,
	TV_THTitle_BGColor VARCHAR(7) NOT NULL,
	TV_THTitle_Color VARCHAR(7) NOT NULL,
	TV_Carattere INT NOT NULL,
	TVRSettings TEXT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE TVRules ADD CONSTRAINT PK_TVRules PRIMARY KEY(TVRId,TVRTournament);
CREATE TABLE CasTeamTarget (
	CTTTournament INT UNSIGNED NOT NULL DEFAULT 0,
	CTTEvent VARCHAR(4) NOT NULL DEFAULT '',
	CTTMatchNo TINYINT UNSIGNED NOT NULL DEFAULT 0,
	CTTTarget VARCHAR(3) NOT NULL,
	CTTSchedule DATETIME NOT NULL
) ENGINE=InnoDB;
ALTER TABLE CasTeamTarget ADD CONSTRAINT PK_CasTeamTarget PRIMARY KEY(CTTEvent,CTTMatchNo,CTTTournament);
CREATE TABLE Classes (
	ClId VARCHAR(2) NOT NULL,
	ClTournament INT UNSIGNED NOT NULL DEFAULT 0,
	ClDescription VARCHAR(32) NOT NULL,
	ClViewOrder TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ClAgeFrom TINYINT NOT NULL,
	ClAgeTo TINYINT NOT NULL,
	ClValidClass VARCHAR(24) NOT NULL DEFAULT '0',
	ClSex TINYINT NOT NULL DEFAULT 0,
	ClAthlete VARCHAR(1) NOT NULL DEFAULT '1',
	ClDivisionsAllowed VARCHAR(255) NOT NULL,
	ClRecClass VARCHAR(4) NOT NULL,
	ClWaClass VARCHAR(4) NOT NULL,
	ClTourRules VARCHAR(75) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Classes ADD CONSTRAINT PK_Classes PRIMARY KEY(ClId,ClTournament);
CREATE INDEX ClTournament ON Classes (ClTournament,ClAthlete,ClViewOrder);
CREATE TABLE HhtEvents (
	HeTournament INT NOT NULL,
	HeEventCode VARCHAR(3) NOT NULL,
	HeHhtId INT NOT NULL,
	HeSession TINYINT NOT NULL,
	HeFinSchedule DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	HeTeamEvent BIT(3) NOT NULL DEFAULT 48
) ENGINE=InnoDB;
ALTER TABLE HhtEvents ADD CONSTRAINT PK_HhtEvents PRIMARY KEY(HeEventCode,HeTournament);
CREATE TABLE DistanceInformation (
	DiTournament INT NOT NULL,
	DiSession TINYINT NOT NULL,
	DiDistance TINYINT NOT NULL,
	DiEnds TINYINT NOT NULL,
	DiArrows TINYINT NOT NULL,
	DiMaxpoints INT NOT NULL,
	DiOptions TEXT NOT NULL,
	DiType VARCHAR(1) NOT NULL DEFAULT 'Q',
	DiDay DATE NOT NULL,
	DiWarmStart TIME NOT NULL,
	DiWarmDuration INT NOT NULL,
	DiStart TIME NOT NULL,
	DiDuration INT NOT NULL,
	DiShift INT DEFAULT NULL,
	DiTargets TEXT NOT NULL,
	DiTourRules VARCHAR(75) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE DistanceInformation ADD CONSTRAINT PK_DistanceInformation PRIMARY KEY(DiDistance,DiSession,DiTournament,DiType);
CREATE INDEX DiDay ON DistanceInformation (DiDay,DiStart,DiDuration);
CREATE INDEX DiDay_2 ON DistanceInformation (DiDay,DiWarmStart,DiWarmDuration);
CREATE TABLE DocumentVersions (
	DvTournament INT NOT NULL,
	DvFile VARCHAR(50) NOT NULL,
	DvEvent VARCHAR(10) NOT NULL,
	DvOrder INT NOT NULL,
	DvSectors VARCHAR(50) NOT NULL,
	DvSector VARCHAR(1) NOT NULL,
	DvMajVersion TINYINT NOT NULL,
	DvMinVersion TINYINT NOT NULL,
	DvPrintDateTime DATETIME NOT NULL,
	DvIncludedDateTime DATETIME NOT NULL,
	DvNotes TEXT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE DocumentVersions ADD CONSTRAINT PK_DocumentVersions PRIMARY KEY(DvEvent,DvFile,DvTournament);
CREATE INDEX DvOrder ON DocumentVersions (DvOrder,DvEvent);
CREATE TABLE iub_items (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) DEFAULT 'NULL',
	description TEXT DEFAULT 'NULL',
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
) ENGINE=InnoDB;
CREATE TABLE HeartBeat (
	HbTournament INT NOT NULL,
	HbEvent VARCHAR(4) NOT NULL,
	HbTeamEvent INT NOT NULL,
	HbMatchNo INT NOT NULL,
	HbValue SMALLINT NOT NULL,
	HbDateTime DATETIME NOT NULL
) ENGINE=InnoDB;
ALTER TABLE HeartBeat ADD CONSTRAINT PK_HeartBeat PRIMARY KEY(HbDateTime,HbEvent,HbMatchNo,HbTeamEvent,HbTournament);
CREATE TABLE Records (
	ReType VARCHAR(2) NOT NULL,
	ReCode VARCHAR(25) NOT NULL,
	ReTeam SMALLINT NOT NULL,
	RePara VARCHAR(1) NOT NULL,
	ReCategory VARCHAR(8) NOT NULL,
	ReTourType SMALLINT NOT NULL,
	ReDistance VARCHAR(5) NOT NULL,
	ReTotal SMALLINT NOT NULL,
	ReXNine SMALLINT NOT NULL,
	ReDate DATE NOT NULL,
	ReExtra TEXT NOT NULL,
	ReLastUpdated DATETIME NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Records ADD CONSTRAINT PK_Records PRIMARY KEY(ReCategory,ReCode,ReDistance,RePara,ReTeam,ReTourType,ReType);
CREATE TABLE Awards (
	AwTournament INT UNSIGNED NOT NULL,
	AwEvent VARCHAR(15) NOT NULL,
	AwFinEvent TINYINT NOT NULL,
	AwTeam TINYINT NOT NULL,
	AwUnrewarded TINYINT NOT NULL,
	AwPositions VARCHAR(16) NOT NULL,
	AwDescription TEXT NOT NULL DEFAULT '',
	AwAwarders TEXT NOT NULL,
	AwAwarderGrouping TEXT NOT NULL,
	AwGroup TINYINT NOT NULL,
	AwOrder TINYINT NOT NULL,
	AwEventTrans VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB;
ALTER TABLE Awards ADD CONSTRAINT PK_Awards PRIMARY KEY(AwEvent,AwFinEvent,AwTeam,AwTournament);
CREATE TABLE GuessWhoData (
	GwdAthlete1 INT NOT NULL,
	GwdAthlete2 INT NOT NULL,
	GwdPlayerCode VARCHAR(20) NOT NULL,
	GwdEvent VARCHAR(5) NOT NULL,
	GwdTeamEvent INT NOT NULL,
	GwdTournament INT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE GuessWhoData ADD CONSTRAINT PK_GuessWhoData PRIMARY KEY(GwdEvent,GwdPlayerCode,GwdTeamEvent,GwdTournament);
CREATE TABLE Rankings (
	RankTournament INT NOT NULL,
	RankCode VARCHAR(25) NOT NULL,
	RankIocCode VARCHAR(5) NOT NULL,
	RankTeam TINYINT NOT NULL,
	RankEvent VARCHAR(4) NOT NULL,
	RankRanking INT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Rankings ADD CONSTRAINT PK_Rankings PRIMARY KEY(RankCode,RankEvent,RankTeam,RankTournament);
CREATE INDEX DvOrder ON Rankings (RankTournament,RankTeam,RankEvent,RankRanking);
CREATE TABLE OnLineIds (
	OliId INT NOT NULL,
	OliType VARCHAR(1) NOT NULL,
	OliServer VARCHAR(50) NOT NULL,
	OliOnlineId INT NOT NULL,
	OliTournament INT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE OnLineIds ADD CONSTRAINT PK_OnLineIds PRIMARY KEY(OliId,OliServer,OliTournament,OliType);
CREATE INDEX OliServer ON OnLineIds (OliServer,OliTournament);
CREATE TABLE Qualifications (
	QuId INT UNSIGNED NOT NULL,
	QuSession TINYINT UNSIGNED NOT NULL DEFAULT 0,
	QuTarget INT NOT NULL,
	QuLetter VARCHAR(1) NOT NULL,
	QuTargetNo VARCHAR(5) NOT NULL,
	QuBacknoPrinted DATETIME NOT NULL,
	QuD1Score SMALLINT NOT NULL,
	QuD1Hits SMALLINT NOT NULL,
	QuD1Gold SMALLINT NOT NULL,
	QuD1Xnine SMALLINT NOT NULL,
	QuD1Arrowstring VARCHAR(90) NOT NULL,
	QuD1Rank SMALLINT NOT NULL,
	QuD1Status TINYINT UNSIGNED NOT NULL,
	QuD2Score SMALLINT NOT NULL,
	QuD2Hits SMALLINT NOT NULL,
	QuD2Gold SMALLINT NOT NULL,
	QuD2Xnine SMALLINT NOT NULL,
	QuD2Arrowstring VARCHAR(90) NOT NULL,
	QuD2Rank SMALLINT NOT NULL,
	QuD2Status TINYINT UNSIGNED NOT NULL,
	QuD3Score SMALLINT NOT NULL,
	QuD3Hits SMALLINT NOT NULL,
	QuD3Gold SMALLINT NOT NULL,
	QuD3Xnine SMALLINT NOT NULL,
	QuD3Arrowstring VARCHAR(90) NOT NULL,
	QuD3Rank SMALLINT NOT NULL,
	QuD3Status TINYINT UNSIGNED NOT NULL,
	QuD4Score SMALLINT NOT NULL,
	QuD4Hits SMALLINT NOT NULL,
	QuD4Gold SMALLINT NOT NULL,
	QuD4Xnine SMALLINT NOT NULL,
	QuD4Arrowstring VARCHAR(255) NOT NULL,
	QuD4Rank SMALLINT NOT NULL,
	QuD4Status TINYINT UNSIGNED NOT NULL,
	QuD5Score SMALLINT NOT NULL,
	QuD5Hits SMALLINT NOT NULL,
	QuD5Gold SMALLINT NOT NULL,
	QuD5Xnine SMALLINT NOT NULL,
	QuD5Arrowstring VARCHAR(36) NOT NULL,
	QuD5Rank SMALLINT NOT NULL,
	QuD5Status TINYINT UNSIGNED NOT NULL,
	QuD6Score SMALLINT NOT NULL,
	QuD6Hits SMALLINT NOT NULL,
	QuD6Gold SMALLINT NOT NULL,
	QuD6Xnine SMALLINT NOT NULL,
	QuD6Arrowstring VARCHAR(36) NOT NULL,
	QuD6Rank SMALLINT NOT NULL,
	QuD6Status TINYINT UNSIGNED NOT NULL,
	QuD7Score SMALLINT NOT NULL,
	QuD7Hits SMALLINT NOT NULL,
	QuD7Gold SMALLINT NOT NULL,
	QuD7Xnine SMALLINT NOT NULL,
	QuD7Arrowstring VARCHAR(36) NOT NULL,
	QuD7Rank SMALLINT NOT NULL,
	QuD7Status TINYINT UNSIGNED NOT NULL,
	QuD8Score SMALLINT NOT NULL,
	QuD8Hits SMALLINT NOT NULL,
	QuD8Gold SMALLINT NOT NULL,
	QuD8Xnine SMALLINT NOT NULL,
	QuD8Arrowstring VARCHAR(36) NOT NULL,
	QuD8Rank SMALLINT NOT NULL,
	QuD8Status TINYINT UNSIGNED NOT NULL,
	QuScore INT NOT NULL,
	QuHits INT NOT NULL,
	QuGold INT NOT NULL,
	QuXnine INT NOT NULL,
	QuArrow TINYINT NOT NULL,
	QuConfirm INT NOT NULL,
	QuClRank SMALLINT NOT NULL,
	QuSubClassRank SMALLINT NOT NULL,
	QuStatus TINYINT UNSIGNED NOT NULL,
	QuTie BIT(3) NOT NULL,
	QuTieBreak VARCHAR(16) NOT NULL,
	QuTimestamp DATETIME DEFAULT NULL,
	QuNotes VARCHAR(50) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Qualifications ADD CONSTRAINT PK_Qualifications PRIMARY KEY(QuId);
CREATE INDEX QuClRank ON Qualifications (QuClRank);
CREATE INDEX QuSession ON Qualifications (QuSession);
CREATE INDEX QuSession_2 ON Qualifications (QuSession,QuTarget,QuLetter);
CREATE INDEX QuSubClassRank ON Qualifications (QuSubClassRank);
CREATE INDEX QuTargetNo ON Qualifications (QuTargetNo);
CREATE TABLE TeamFinals (
	TfEvent VARCHAR(4) NOT NULL,
	TfMatchNo TINYINT UNSIGNED NOT NULL DEFAULT 0,
	TfTournament INT UNSIGNED NOT NULL DEFAULT 0,
	TfSession TINYINT UNSIGNED NOT NULL DEFAULT 0,
	TfTarget VARCHAR(6) NOT NULL,
	TfScheduledtime DATETIME NOT NULL,
	TfRank TINYINT UNSIGNED NOT NULL DEFAULT 0,
	TfTeam INT UNSIGNED NOT NULL DEFAULT 0,
	TfSubTeam TINYINT NOT NULL,
	TfScore SMALLINT NOT NULL DEFAULT 0,
	TfSetScore TINYINT NOT NULL DEFAULT 0,
	TfSetPoints VARCHAR(36) NOT NULL,
	TfSetPointsByEnd VARCHAR(36) NOT NULL,
	TfWinnerSet TINYINT NOT NULL DEFAULT 0,
	TfTie BIT(3) NOT NULL DEFAULT 48,
	TfArrowstring VARCHAR(90) NOT NULL,
	TfTiebreak VARCHAR(30) NOT NULL,
	TfArrowPosition TEXT NOT NULL,
	TfTiePosition TEXT NOT NULL,
	TfWinLose BIT(3) NOT NULL DEFAULT 48,
	TfFinalRank TINYINT UNSIGNED NOT NULL DEFAULT 0,
	TfDateTime DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	TfSyncro DATETIME NOT NULL,
	TfLive TINYINT NOT NULL DEFAULT 0,
	TfStatus TINYINT NOT NULL DEFAULT 0,
	TfShootFirst TINYINT NOT NULL,
	TfShootingArchers TEXT NOT NULL,
	TfVxF TINYINT NOT NULL DEFAULT 0,
	TfConfirmed INT NOT NULL,
	TfNotes VARCHAR(30) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE TeamFinals ADD CONSTRAINT PK_TeamFinals PRIMARY KEY(TfEvent,TfMatchNo,TfTournament);
CREATE INDEX TfDateTime ON TeamFinals (TfTournament,TfDateTime);
CREATE INDEX TfLive ON TeamFinals (TfLive,TfTournament);
CREATE TABLE Targets (
	TarId TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TarDescr VARCHAR(24) NOT NULL,
	TarArray VARCHAR(24) NOT NULL DEFAULT '0',
	TarStars VARCHAR(10) NOT NULL,
	TarOrder INT NOT NULL,
	TarFullSize INT NOT NULL,
	A_size INT NOT NULL,
	A_color VARCHAR(6) NOT NULL,
	B_size INT NOT NULL,
	B_color VARCHAR(6) NOT NULL,
	C_size INT NOT NULL,
	C_color VARCHAR(6) NOT NULL,
	D_size INT NOT NULL,
	D_color VARCHAR(6) NOT NULL,
	E_size INT NOT NULL,
	E_color VARCHAR(6) NOT NULL,
	F_size INT NOT NULL,
	F_color VARCHAR(6) NOT NULL,
	G_size INT NOT NULL,
	G_color VARCHAR(6) NOT NULL,
	H_size INT NOT NULL,
	H_color VARCHAR(6) NOT NULL,
	I_size INT NOT NULL,
	I_color VARCHAR(6) NOT NULL,
	J_size INT NOT NULL,
	J_color VARCHAR(6) NOT NULL,
	K_size INT NOT NULL,
	K_color VARCHAR(6) NOT NULL,
	L_size INT NOT NULL,
	L_color VARCHAR(6) NOT NULL,
	M_size INT NOT NULL,
	M_color VARCHAR(6) NOT NULL,
	N_size INT NOT NULL,
	N_color VARCHAR(6) NOT NULL,
	O_size INT NOT NULL,
	O_color VARCHAR(6) NOT NULL,
	P_size INT NOT NULL,
	P_color VARCHAR(6) NOT NULL,
	Q_size INT NOT NULL,
	Q_color VARCHAR(6) NOT NULL,
	R_size INT NOT NULL,
	R_color VARCHAR(6) NOT NULL,
	S_size INT NOT NULL,
	S_color VARCHAR(6) NOT NULL,
	T_size INT NOT NULL,
	T_color VARCHAR(6) NOT NULL,
	U_size INT NOT NULL,
	U_color VARCHAR(6) NOT NULL,
	V_size INT NOT NULL,
	V_color VARCHAR(6) NOT NULL,
	W_size INT NOT NULL,
	W_color VARCHAR(6) NOT NULL,
	X_size INT NOT NULL,
	X_color VARCHAR(6) NOT NULL,
	Y_size INT NOT NULL,
	Y_color VARCHAR(6) NOT NULL,
	Z_size INT NOT NULL,
	Z_color VARCHAR(6) NOT NULL,
	TarDummyLine INT NOT NULL
) ENGINE=InnoDB;
CREATE TABLE Individuals (
	IndId INT UNSIGNED NOT NULL,
	IndEvent VARCHAR(4) NOT NULL,
	IndTournament INT NOT NULL,
	IndD1Rank SMALLINT NOT NULL,
	IndD2Rank SMALLINT NOT NULL,
	IndD3Rank SMALLINT NOT NULL,
	IndD4Rank SMALLINT NOT NULL,
	IndD5Rank SMALLINT NOT NULL,
	IndD6Rank SMALLINT NOT NULL,
	IndD7Rank SMALLINT NOT NULL,
	IndD8Rank SMALLINT NOT NULL,
	IndRank SMALLINT NOT NULL,
	IndRankFinal SMALLINT NOT NULL,
	IndSO SMALLINT NOT NULL DEFAULT 0,
	IndTieBreak VARCHAR(8) NOT NULL,
	IndTimestamp DATETIME DEFAULT NULL,
	IndTimestampFinal DATETIME DEFAULT NULL,
	IndBacknoPrinted DATETIME NOT NULL,
	IndNotes VARCHAR(50) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Individuals ADD CONSTRAINT PK_Individuals PRIMARY KEY(IndEvent,IndId,IndTournament);
CREATE INDEX IndEvent ON Individuals (IndEvent,IndTournament,IndRankFinal,IndRank);
CREATE TABLE ExtraDataCountries (
	EdcId INT NOT NULL,
	EdcSubTeam TINYINT NOT NULL,
	EdcType VARCHAR(10) NOT NULL,
	EdcEvent VARCHAR(4) NOT NULL,
	EdcEmail VARCHAR(100) NOT NULL,
	EdcExtra TEXT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE ExtraDataCountries ADD CONSTRAINT PK_ExtraDataCountries PRIMARY KEY(EdcEvent,EdcId,EdcSubTeam,EdcType);
CREATE TABLE HTTData (
	HtdEnId INT UNSIGNED NOT NULL,
	HtdMatchNo TINYINT UNSIGNED DEFAULT NULL,
	HtdEvent VARCHAR(4) NOT NULL DEFAULT '',
	HtdTargetNo VARCHAR(5) NOT NULL,
	HtdDistance TINYINT NOT NULL,
	HtdFinScheduling DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	HtdTeamEvent BIT(3) NOT NULL DEFAULT 48,
	HtdArrowStart TINYINT NOT NULL,
	HtdArrowEnd TINYINT NOT NULL,
	HtdArrowString VARCHAR(6) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE HTTData ADD CONSTRAINT PK_HTTData PRIMARY KEY(HtdArrowStart,HtdDistance,HtdFinScheduling,HtdTargetNo,HtdTeamEvent);
CREATE TABLE Session (
	SesTournament INT UNSIGNED NOT NULL,
	SesOrder TINYINT UNSIGNED NOT NULL DEFAULT 0,
	SesType VARCHAR(1) NOT NULL DEFAULT 'Q',
	SesName VARCHAR(100) NOT NULL DEFAULT '',
	SesTar4Session INT NOT NULL,
	SesAth4Target TINYINT UNSIGNED NOT NULL DEFAULT 0,
	SesFirstTarget INT NOT NULL,
	SesFollow BIT(3) NOT NULL DEFAULT 48,
	SesStatus TINYINT NOT NULL DEFAULT 0,
	SesDtStart DATETIME NOT NULL,
	SesDtEnd DATETIME NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Session ADD CONSTRAINT PK_Session PRIMARY KEY(SesOrder,SesTournament,SesType);
CREATE TABLE FinGroups (
	FGId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FGTournament INT UNSIGNED NOT NULL DEFAULT 0,
	FGDescr VARCHAR(24) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IdCards (
	IcTournament INT NOT NULL,
	IcBackground LONGBLOB NOT NULL,
	IcSettings TEXT NOT NULL,
	IcNumber INT NOT NULL,
	IcType VARCHAR(1) NOT NULL DEFAULT 'A',
	IcName VARCHAR(50) NOT NULL DEFAULT 'Accreditation'
) ENGINE=InnoDB;
ALTER TABLE IdCards ADD CONSTRAINT PK_IdCards PRIMARY KEY(IcNumber,IcTournament,IcType);
CREATE INDEX IcTournament ON IdCards (IcTournament,IcNumber);
CREATE TABLE CasScore (
	CaSTournament INT UNSIGNED NOT NULL DEFAULT 0,
	CaSPhase TINYINT UNSIGNED NOT NULL DEFAULT 0,
	CaSRound TINYINT UNSIGNED NOT NULL,
	CaSMatchNo TINYINT UNSIGNED NOT NULL,
	CaSEventCode VARCHAR(4) NOT NULL,
	CaSTarget VARCHAR(3) NOT NULL,
	CaSSetPoints VARCHAR(23) NOT NULL DEFAULT '',
	CaSSetPointsByEnd VARCHAR(23) NOT NULL,
	CaSSetScore TINYINT NOT NULL DEFAULT 0,
	CaSScore SMALLINT NOT NULL DEFAULT 0,
	CaSTie BIT(3) NOT NULL DEFAULT 48,
	CaSWinLose TINYINT NOT NULL,
	CaSArrowString VARCHAR(36) NOT NULL,
	CaSArrowPosition VARCHAR(360) NOT NULL,
	CaSTiebreak VARCHAR(9) NOT NULL,
	CaSTiePosition VARCHAR(90) NOT NULL,
	CaSPoints TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB;
ALTER TABLE CasScore ADD CONSTRAINT PK_CasScore PRIMARY KEY(CaSEventCode,CaSMatchNo,CaSPhase,CaSRound,CaSTournament);
CREATE TABLE CasGrid (
	CGPhase TINYINT UNSIGNED NOT NULL,
	CGRound TINYINT UNSIGNED NOT NULL,
	CGMatchNo1 TINYINT UNSIGNED NOT NULL,
	CGMatchNo2 TINYINT UNSIGNED NOT NULL,
	CGGroup TINYINT UNSIGNED NOT NULL
) ENGINE=InnoDB;
ALTER TABLE CasGrid ADD CONSTRAINT PK_CasGrid PRIMARY KEY(CGMatchNo1,CGMatchNo2,CGPhase,CGRound);
CREATE TABLE ClubTeamRankMatch (
	CTRMEventPhase TINYINT NOT NULL,
	CTRMRank TINYINT NOT NULL,
	CTRMMatchNo TINYINT UNSIGNED NOT NULL
) ENGINE=InnoDB;
ALTER TABLE ClubTeamRankMatch ADD CONSTRAINT PK_ClubTeamRankMatch PRIMARY KEY(CTRMEventPhase,CTRMRank);
CREATE TABLE AclDetails (
	AclDtTournament INT NOT NULL,
	AclDtIP VARCHAR(15) NOT NULL,
	AclDtFeature TINYINT NOT NULL DEFAULT 0,
	AclDtLevel TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB;
ALTER TABLE AclDetails ADD CONSTRAINT PK_AclDetails PRIMARY KEY(AclDtFeature,AclDtIP,AclDtTournament);
CREATE TABLE BackNumber (
	BnTournament INT UNSIGNED NOT NULL,
	BnFinal TINYINT NOT NULL,
	BnHeight SMALLINT UNSIGNED NOT NULL,
	BnWidth SMALLINT UNSIGNED NOT NULL,
	BnBackground MEDIUMBLOB NOT NULL,
	BnBgX SMALLINT NOT NULL,
	BnBgY SMALLINT NOT NULL,
	BnBgW SMALLINT NOT NULL,
	BnBgH SMALLINT NOT NULL,
	BnTargetNo TINYINT UNSIGNED NOT NULL,
	BnTnoColor VARCHAR(6) NOT NULL DEFAULT '000000',
	BnTnoSize SMALLINT NOT NULL,
	BnTnoX SMALLINT NOT NULL,
	BnTnoY SMALLINT NOT NULL,
	BnTnoW SMALLINT NOT NULL,
	BnTnoH SMALLINT NOT NULL,
	BnAthlete TINYINT UNSIGNED NOT NULL,
	BnAthColor VARCHAR(6) NOT NULL DEFAULT '000000',
	BnAthSize SMALLINT NOT NULL,
	BnAthX SMALLINT NOT NULL,
	BnAthY SMALLINT NOT NULL,
	BnAthW SMALLINT NOT NULL,
	BnAthH SMALLINT NOT NULL,
	BnCountry TINYINT UNSIGNED NOT NULL,
	BnCoColor VARCHAR(6) NOT NULL DEFAULT '000000',
	BnCoSize SMALLINT NOT NULL,
	BnCoX SMALLINT NOT NULL,
	BnCoY SMALLINT NOT NULL,
	BnCoW SMALLINT NOT NULL,
	BnCoH SMALLINT NOT NULL,
	BnOffsetX SMALLINT NOT NULL,
	BnOffsetY SMALLINT NOT NULL,
	BnCapitalFirstName VARCHAR(1) NOT NULL,
	BnGivenNameInitial VARCHAR(1) NOT NULL,
	BnCountryCodeOnly VARCHAR(1) NOT NULL,
	BnIncludeSession TINYINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE BackNumber ADD CONSTRAINT PK_BackNumber PRIMARY KEY(BnFinal,BnTournament);
CREATE TABLE Tournament (
	ToId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ToOnlineId INT NOT NULL DEFAULT 0,
	ToType SMALLINT UNSIGNED NOT NULL,
	ToCode VARCHAR(8) NOT NULL,
	ToIocCode VARCHAR(5) NOT NULL DEFAULT '',
	ToTimeZone VARCHAR(50) NOT NULL DEFAULT '',
	ToName TINYTEXT NOT NULL,
	ToNameShort VARCHAR(60) NOT NULL,
	ToCommitee VARCHAR(10) NOT NULL,
	ToComDescr TINYTEXT NOT NULL,
	ToWhere TINYTEXT NOT NULL,
	ToVenue TINYTEXT NOT NULL,
	ToWhenFrom DATE NOT NULL,
	ToWhenTo DATE NOT NULL,
	ToIntEvent TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ToCurrency VARCHAR(8) DEFAULT 'NULL',
	ToPrintLang VARCHAR(5) NOT NULL,
	ToPrintChars TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ToPrintPaper TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ToImpFin TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ToImgL BLOB NOT NULL,
	ToImgR BLOB NOT NULL,
	ToImgB BLOB NOT NULL,
	ToImgB2 BLOB NOT NULL,
	ToNumSession TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ToIndFinVxA TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ToTeamFinVxA TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ToDbVersion DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	ToBlock INT UNSIGNED NOT NULL,
	ToUseHHT TINYINT NOT NULL DEFAULT 0,
	ToLocRule VARCHAR(16) NOT NULL DEFAULT '',
	ToTypeName VARCHAR(25) NOT NULL,
	ToTypeSubRule VARCHAR(25) NOT NULL,
	ToNumDist TINYINT UNSIGNED NOT NULL,
	ToNumEnds TINYINT UNSIGNED NOT NULL,
	ToMaxDistScore MEDIUMINT UNSIGNED NOT NULL,
	ToMaxFinIndScore MEDIUMINT UNSIGNED NOT NULL,
	ToMaxFinTeamScore MEDIUMINT UNSIGNED NOT NULL,
	ToCategory TINYINT NOT NULL DEFAULT 0,
	ToElabTeam TINYINT NOT NULL DEFAULT 0,
	ToElimination TINYINT NOT NULL DEFAULT 0,
	ToGolds VARCHAR(5) NOT NULL,
	ToXNine VARCHAR(5) NOT NULL,
	ToGoldsChars VARCHAR(16) NOT NULL DEFAULT '',
	ToXNineChars VARCHAR(16) NOT NULL DEFAULT '',
	ToDouble TINYINT NOT NULL DEFAULT 0,
	ToCollation VARCHAR(15) NOT NULL,
	ToIsORIS VARCHAR(1) NOT NULL DEFAULT '',
	ToOptions TEXT NOT NULL,
	ToRecCode VARCHAR(25) NOT NULL
) ENGINE=InnoDB;
CREATE UNIQUE INDEX ToCode ON Tournament (ToCode);
CREATE INDEX ToDbVersion ON Tournament (ToDbVersion);
CREATE TABLE FinalReportQ (
	FrqId VARCHAR(5) NOT NULL,
	FrqStatus TINYINT NOT NULL DEFAULT 0,
	FrqQuestion TINYTEXT NOT NULL,
	FrqTip TEXT NOT NULL,
	FrqType TINYINT NOT NULL,
	FrqOptions VARCHAR(200) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE FinalReportQ ADD CONSTRAINT PK_FinalReportQ PRIMARY KEY(FrqId);
CREATE TABLE SubClass (
	ScId VARCHAR(2) NOT NULL,
	ScTournament INT UNSIGNED NOT NULL DEFAULT 0,
	ScDescription VARCHAR(32) NOT NULL,
	ScViewOrder TINYINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB;
ALTER TABLE SubClass ADD CONSTRAINT PK_SubClass PRIMARY KEY(ScId,ScTournament);
CREATE TABLE ClubTeamScore (
	CTSTournament INT UNSIGNED NOT NULL DEFAULT 0,
	CTSPhase TINYINT UNSIGNED NOT NULL DEFAULT 0,
	CTSRound TINYINT UNSIGNED NOT NULL,
	CTSMatchNo TINYINT UNSIGNED NOT NULL,
	CTSEventCode VARCHAR(4) NOT NULL,
	CTSPrimary TINYINT UNSIGNED NOT NULL,
	CTSTarget VARCHAR(2) NOT NULL,
	CTSScore SMALLINT NOT NULL DEFAULT 0,
	CTSTie BIT(3) NOT NULL DEFAULT 48,
	CTSArrowString VARCHAR(24) NOT NULL,
	CTSArrowPosition VARCHAR(240) NOT NULL,
	CTSTiebreak VARCHAR(9) NOT NULL,
	CTSTiePosition VARCHAR(90) NOT NULL,
	CTSPoints TINYINT NOT NULL DEFAULT 0,
	CTSSetPoints INT NOT NULL,
	CTSSetEnds VARCHAR(36) DEFAULT 'NULL',
	CTSDateTime DATETIME NOT NULL,
	CTSTimeStamp DATETIME NOT NULL
) ENGINE=InnoDB;
ALTER TABLE ClubTeamScore ADD CONSTRAINT PK_ClubTeamScore PRIMARY KEY(CTSEventCode,CTSMatchNo,CTSPhase,CTSPrimary,CTSRound,CTSTournament);
CREATE TABLE iub_schema_migrations (
	version VARCHAR(255) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE iub_schema_migrations ADD CONSTRAINT PK_iub_schema_migrations PRIMARY KEY(version);
CREATE TABLE ElabQualifications (
	EqId INT UNSIGNED NOT NULL,
	EqArrowNo SMALLINT UNSIGNED NOT NULL,
	EqDistance TINYINT UNSIGNED NOT NULL,
	EqScore INT NOT NULL,
	EqHits INT NOT NULL,
	EqGold INT NOT NULL,
	EqXnine INT NOT NULL,
	EqTimestamp DATETIME DEFAULT NULL
) ENGINE=InnoDB;
ALTER TABLE ElabQualifications ADD CONSTRAINT PK_ElabQualifications PRIMARY KEY(EqArrowNo,EqDistance,EqId);
CREATE TABLE ExtraData (
	EdId INT NOT NULL,
	EdType VARCHAR(10) NOT NULL,
	EdEvent VARCHAR(4) NOT NULL,
	EdEmail VARCHAR(100) NOT NULL,
	EdExtra TEXT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE ExtraData ADD CONSTRAINT PK_ExtraData PRIMARY KEY(EdEvent,EdId,EdType);
CREATE TABLE GateLog (
	GLEntry INT NOT NULL,
	GLDateTime DATETIME NOT NULL,
	GLIP VARCHAR(15) NOT NULL,
	GLDirection TINYINT NOT NULL,
	GLTournament INT NOT NULL,
	GLStatus TINYINT NOT NULL
) ENGINE=InnoDB;
CREATE INDEX GLDateTime ON GateLog (GLDateTime);
CREATE INDEX GLEntry ON GateLog (GLEntry);
CREATE INDEX GLTournament ON GateLog (GLTournament,GLEntry);
CREATE TABLE TournamentInvolved (
	TiId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TiTournament INT UNSIGNED NOT NULL,
	TiType SMALLINT UNSIGNED NOT NULL,
	TiCode VARCHAR(9) NOT NULL,
	TiName VARCHAR(64) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE Photos (
	PhEnId INT UNSIGNED NOT NULL,
	PhPhoto LONGBLOB NOT NULL,
	PhPhotoEntered TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	PhToRetake TINYINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Photos ADD CONSTRAINT PK_Photos PRIMARY KEY(PhEnId);
CREATE INDEX PhPhotoEntered ON Photos (PhPhotoEntered);
CREATE TABLE BoinxSchedule (
	BsTournament INT NOT NULL,
	BsType VARCHAR(25) NOT NULL,
	BsExtra VARCHAR(25) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE BoinxSchedule ADD CONSTRAINT PK_BoinxSchedule PRIMARY KEY(BsTournament,BsType);
CREATE TABLE CasTeamFinal (
	CTFEvent VARCHAR(4) NOT NULL,
	CTFMatchNo TINYINT UNSIGNED NOT NULL DEFAULT 0,
	CTFTournament INT UNSIGNED NOT NULL DEFAULT 0,
	CTFSetPoints VARCHAR(23) NOT NULL,
	CTFSetScore TINYINT NOT NULL DEFAULT 0,
	CTFScore SMALLINT NOT NULL DEFAULT 0,
	CTFTie BIT(3) NOT NULL DEFAULT 48,
	CTFArrowString VARCHAR(36) NOT NULL,
	CTFTieBreak VARCHAR(3) NOT NULL,
	CTFTiePoins VARCHAR(5) NOT NULL,
	CTFTieScore SMALLINT NOT NULL DEFAULT 0,
	CTFScore2 SMALLINT NOT NULL DEFAULT 0
) ENGINE=InnoDB;
ALTER TABLE CasTeamFinal ADD CONSTRAINT PK_CasTeamFinal PRIMARY KEY(CTFEvent,CTFMatchNo,CTFTournament);
CREATE TABLE IdCardElements (
	IceTournament INT NOT NULL,
	IceOrder INT NOT NULL,
	IceType VARCHAR(25) NOT NULL,
	IceContent LONGBLOB NOT NULL,
	IceMimeType VARCHAR(25) NOT NULL,
	IceOptions TEXT NOT NULL,
	IceNewOrder INT NOT NULL,
	IceCardNumber INT NOT NULL,
	IceCardType VARCHAR(1) NOT NULL DEFAULT 'A'
) ENGINE=InnoDB;
CREATE INDEX IceTournament ON IdCardElements (IceTournament,IceOrder);
CREATE INDEX IceTournament_2 ON IdCardElements (IceTournament,IceCardNumber,IceOrder);
CREATE INDEX IceTournament_3 ON IdCardElements (IceTournament,IceCardType,IceCardNumber,IceOrder);
CREATE TABLE iub_ar_internal_metadata (
	key VARCHAR(255) NOT NULL,
	value VARCHAR(255) DEFAULT 'NULL',
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL
) ENGINE=InnoDB;
ALTER TABLE iub_ar_internal_metadata ADD CONSTRAINT PK_iub_ar_internal_metadata PRIMARY KEY(key);
CREATE TABLE ClubTeamGrid (
	CTGPhase TINYINT UNSIGNED NOT NULL,
	CTGRound TINYINT UNSIGNED NOT NULL,
	CTGMatchNo1 TINYINT UNSIGNED NOT NULL,
	CTGMatchNo2 TINYINT UNSIGNED NOT NULL,
	CTGGroup TINYINT UNSIGNED NOT NULL
) ENGINE=InnoDB;
ALTER TABLE ClubTeamGrid ADD CONSTRAINT PK_ClubTeamGrid PRIMARY KEY(CTGMatchNo1,CTGMatchNo2,CTGPhase,CTGRound);
CREATE TABLE Emails (
	EmTournament INT NOT NULL,
	EmTitle VARCHAR(20) NOT NULL,
	EmSubject VARCHAR(60) NOT NULL,
	EmBody TEXT NOT NULL,
	EmFilter TEXT NOT NULL,
	EmSentDate DATETIME NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Emails ADD CONSTRAINT PK_Emails PRIMARY KEY(EmTitle,EmTournament);
CREATE TABLE Eliminations (
	ElId INT UNSIGNED NOT NULL,
	ElElimPhase TINYINT NOT NULL DEFAULT 0,
	ElEventCode VARCHAR(4) NOT NULL,
	ElTournament INT UNSIGNED NOT NULL,
	ElQualRank SMALLINT NOT NULL,
	ElSession TINYINT UNSIGNED NOT NULL DEFAULT 0,
	ElTargetNo VARCHAR(5) NOT NULL,
	ElScore SMALLINT NOT NULL,
	ElHits SMALLINT NOT NULL,
	ElGold SMALLINT NOT NULL,
	ElXnine SMALLINT NOT NULL,
	ElArrowString VARCHAR(36) NOT NULL,
	ElTiebreak VARCHAR(8) NOT NULL,
	ElConfirm INT NOT NULL,
	ElRank TINYINT UNSIGNED NOT NULL,
	ElSO SMALLINT NOT NULL DEFAULT 0,
	ElStatus TINYINT UNSIGNED NOT NULL,
	ElDateTime DATETIME NOT NULL,
	ElBacknoPrinted DATETIME NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Eliminations ADD CONSTRAINT PK_Eliminations PRIMARY KEY(ElElimPhase,ElEventCode,ElQualRank,ElTournament);
CREATE INDEX ElAthleteEventTournament ON Eliminations (ElId,ElEventCode,ElTournament);
CREATE INDEX ElDateTime ON Eliminations (ElTournament,ElDateTime);
CREATE INDEX ElId ON Eliminations (ElId,ElElimPhase);
CREATE TABLE GuessWho (
	GwPlayerCode VARCHAR(20) NOT NULL,
	GwPlayerPass VARCHAR(20) NOT NULL,
	GwPlayerName VARCHAR(50) NOT NULL,
	GwPlayerPhone VARCHAR(30) NOT NULL,
	GwTournament INT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE GuessWho ADD CONSTRAINT PK_GuessWho PRIMARY KEY(GwPlayerCode,GwTournament);
CREATE TABLE Events (
	EvCode VARCHAR(4) NOT NULL,
	EvTeamEvent BIT(3) NOT NULL,
	EvTournament INT NOT NULL,
	EvEventName VARCHAR(64) NOT NULL,
	EvProgr INT NOT NULL,
	EvShootOff TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvE1ShootOff TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvE2ShootOff TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvSession INT NOT NULL,
	EvPrint BIT(3) NOT NULL,
	EvQualPrintHead VARCHAR(64) NOT NULL,
	EvQualLastUpdate DATETIME DEFAULT NULL,
	EvFinalFirstPhase TINYINT NOT NULL,
	EvWinnerFinalRank INT NOT NULL DEFAULT 1,
	EvNumQualified INT NOT NULL,
	EvFirstQualified INT DEFAULT 1,
	EvFinalPrintHead VARCHAR(64) NOT NULL,
	EvFinalLastUpdate DATETIME DEFAULT NULL,
	EvFinalTargetType TINYINT NOT NULL,
	EvGolds VARCHAR(5) NOT NULL,
	EvXNine VARCHAR(5) NOT NULL,
	EvGoldsChars VARCHAR(16) NOT NULL,
	EvXNineChars VARCHAR(16) NOT NULL,
	EvTargetSize INT NOT NULL DEFAULT 0,
	EvDistance VARCHAR(6) NOT NULL,
	EvFinalAthTarget TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvElimType TINYINT NOT NULL,
	EvElim1 TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvE1Ends TINYINT NOT NULL,
	EvE1Arrows TINYINT NOT NULL,
	EvE1SO TINYINT NOT NULL,
	EvElim2 TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvE2Ends TINYINT NOT NULL,
	EvE2Arrows TINYINT NOT NULL,
	EvE2SO TINYINT NOT NULL,
	EvPartialTeam BIT(3) NOT NULL DEFAULT 48,
	EvMultiTeam BIT(3) NOT NULL DEFAULT 48,
	EvMixedTeam TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvTeamCreationMode TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvMaxTeamPerson TINYINT NOT NULL DEFAULT 1,
	EvRunning TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvMatchMode TINYINT NOT NULL DEFAULT 0,
	EvMatchArrowsNo TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvElimEnds TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvElimArrows TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvElimSO TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvFinEnds TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvFinArrows TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvFinSO TINYINT UNSIGNED NOT NULL DEFAULT 0,
	EvRecCategory VARCHAR(8) NOT NULL,
	EvWaCategory VARCHAR(8) NOT NULL,
	EvMedals TINYINT NOT NULL DEFAULT 1,
	EvTourRules VARCHAR(75) NOT NULL,
	EvCodeParent VARCHAR(4) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Events ADD CONSTRAINT PK_Events PRIMARY KEY(EvCode,EvTeamEvent,EvTournament);
CREATE INDEX EvTournament ON Events (EvTournament,EvTeamEvent,EvCode);
CREATE TABLE EventClass (
	EcCode VARCHAR(4) NOT NULL,
	EcTeamEvent BIT(3) NOT NULL DEFAULT 48,
	EcTournament INT NOT NULL,
	EcClass VARCHAR(2) NOT NULL,
	EcDivision VARCHAR(2) NOT NULL,
	EcSubClass VARCHAR(2) NOT NULL,
	EcNumber TINYINT UNSIGNED NOT NULL DEFAULT 1,
	EcTourRules VARCHAR(75) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE EventClass ADD CONSTRAINT PK_EventClass PRIMARY KEY(EcClass,EcCode,EcDivision,EcSubClass,EcTeamEvent,EcTournament);
CREATE INDEX MakeIndividuals ON EventClass (EcTeamEvent,EcTournament,EcClass,EcDivision);
CREATE TABLE TourTypes (
	TtId INT NOT NULL,
	TtType VARCHAR(35) NOT NULL,
	TtDistance INT NOT NULL,
	TtOrderBy INT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE TourTypes ADD CONSTRAINT PK_TourTypes PRIMARY KEY(TtId);
CREATE TABLE Scheduler (
	SchTournament INT UNSIGNED NOT NULL,
	SchOrder TINYINT UNSIGNED NOT NULL DEFAULT 1,
	SchDateStart DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	SchDateEnd DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	SchSesOrder TINYINT UNSIGNED NOT NULL DEFAULT 0,
	SchSesType VARCHAR(1) NOT NULL DEFAULT 'Z',
	SchDescr VARCHAR(255) NOT NULL DEFAULT '',
	SchDay DATE NOT NULL,
	SchStart TIME NOT NULL,
	SchDuration INT NOT NULL,
	SchTitle VARCHAR(255) NOT NULL,
	SchSubTitle VARCHAR(255) NOT NULL,
	SchText VARCHAR(255) NOT NULL,
	SchShift INT DEFAULT NULL,
	SchTargets TEXT NOT NULL,
	SchLink VARCHAR(100) NOT NULL,
	SchTimestamp TIMESTAMP NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB;
ALTER TABLE Scheduler ADD CONSTRAINT PK_Scheduler PRIMARY KEY(SchDay,SchOrder,SchStart,SchTournament);
CREATE INDEX SchTournament ON Scheduler (SchTournament,SchDay,SchStart);
CREATE TABLE HhtSetup (
	HsId INT NOT NULL,
	HsTournament INT NOT NULL,
	HsIpAddress VARCHAR(15) NOT NULL,
	HsPort VARCHAR(6) NOT NULL,
	HsName VARCHAR(16) NOT NULL,
	HsMode TINYINT NOT NULL,
	HsFlags VARCHAR(16) NOT NULL,
	HsPhase VARCHAR(20) NOT NULL,
	HsSequence VARCHAR(12) NOT NULL,
	HsDistance TINYINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE HhtSetup ADD CONSTRAINT PK_HhtSetup PRIMARY KEY(HsId,HsTournament);
CREATE TABLE CasGroupMatch (
	CaGMGroup TINYINT UNSIGNED NOT NULL,
	CaGRank TINYINT UNSIGNED NOT NULL,
	CaGMMatchNo TINYINT UNSIGNED NOT NULL
) ENGINE=InnoDB;
ALTER TABLE CasGroupMatch ADD CONSTRAINT PK_CasGroupMatch PRIMARY KEY(CaGMGroup,CaGMMatchNo,CaGRank);
CREATE TABLE AclFeatures (
	AclFeId TINYINT NOT NULL,
	AclFeName VARCHAR(50) NOT NULL
) ENGINE=InnoDB;
CREATE UNIQUE INDEX AclFeId ON AclFeatures (AclFeId);
CREATE UNIQUE INDEX AclFeName ON AclFeatures (AclFeName);
CREATE TABLE Phases (
	PhId TINYINT NOT NULL DEFAULT 0,
	PhDescr VARCHAR(64) NOT NULL DEFAULT '',
	PhLevel TINYINT NOT NULL DEFAULT -1,
	PhIndTeam TINYINT NOT NULL,
	PhRuleSets TINYTEXT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Phases ADD CONSTRAINT PK_Phases PRIMARY KEY(PhId);
CREATE INDEX PhId ON Phases (PhId,PhRuleSets);
CREATE TABLE FinTraining (
	FtTournament INT UNSIGNED NOT NULL,
	FtScheduledDate DATE NOT NULL,
	FtScheduledTime TIME NOT NULL,
	FtScheduledLen SMALLINT NOT NULL DEFAULT 0,
	FtTargetFrom VARCHAR(3) NOT NULL,
	FtTargetTo VARCHAR(3) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE FinTraining ADD CONSTRAINT PK_FinTraining PRIMARY KEY(FtScheduledDate,FtScheduledTime,FtTargetFrom,FtTournament);
CREATE TABLE Images (
	ImTournament INT NOT NULL,
	ImIocCode VARCHAR(5) NOT NULL,
	ImSection VARCHAR(5) NOT NULL,
	ImReference VARCHAR(11) NOT NULL,
	ImType VARCHAR(3) NOT NULL,
	ImContent MEDIUMBLOB NOT NULL,
	ImgLastUpdate TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	ImChecked VARCHAR(1) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Images ADD CONSTRAINT PK_Images PRIMARY KEY(ImIocCode,ImReference,ImSection,ImTournament,ImType);
CREATE TABLE Finals (
	FinEvent VARCHAR(4) NOT NULL,
	FinMatchNo TINYINT UNSIGNED NOT NULL DEFAULT 0,
	FinTournament INT UNSIGNED NOT NULL DEFAULT 0,
	FinRank TINYINT UNSIGNED NOT NULL DEFAULT 0,
	FinAthlete INT UNSIGNED NOT NULL DEFAULT 0,
	FinScore SMALLINT NOT NULL DEFAULT 0,
	FinSetScore TINYINT NOT NULL DEFAULT 0,
	FinSetPoints VARCHAR(36) NOT NULL,
	FinSetPointsByEnd VARCHAR(36) NOT NULL,
	FinWinnerSet TINYINT NOT NULL DEFAULT 0,
	FinTie BIT(3) NOT NULL DEFAULT 48,
	FinArrowstring VARCHAR(60) NOT NULL,
	FinTiebreak VARCHAR(10) NOT NULL,
	FinArrowPosition TEXT NOT NULL,
	FinTiePosition TEXT NOT NULL,
	FinWinLose BIT(3) NOT NULL DEFAULT 48,
	FinFinalRank TINYINT UNSIGNED NOT NULL DEFAULT 0,
	FinDateTime DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	FinSyncro DATETIME NOT NULL,
	FinLive TINYINT NOT NULL DEFAULT 0,
	FinStatus TINYINT NOT NULL DEFAULT 0,
	FinShootFirst TINYINT NOT NULL,
	FinVxF TINYINT NOT NULL DEFAULT 0,
	FinTarget VARCHAR(5) NOT NULL,
	FinConfirmed INT NOT NULL,
	FinNotes VARCHAR(30) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Finals ADD CONSTRAINT PK_Finals PRIMARY KEY(FinEvent,FinMatchNo,FinTournament);
CREATE INDEX FinAthleteEventTournament ON Finals (FinAthlete,FinEvent,FinTournament);
CREATE INDEX FinDateTime ON Finals (FinTournament,FinDateTime);
CREATE INDEX FinLive ON Finals (FinLive,FinTournament);
CREATE INDEX FinTournament ON Finals (FinTournament,FinEvent,FinAthlete,FinMatchNo);
CREATE TABLE Vegas (
	VeId INT UNSIGNED NOT NULL,
	VeArrowstring VARCHAR(90) NOT NULL,
	VeScore SMALLINT NOT NULL,
	VeX SMALLINT NOT NULL,
	VeRank SMALLINT NOT NULL,
	VeSubClass VARCHAR(2) NOT NULL,
	VeTimestamp DATETIME DEFAULT NULL
) ENGINE=InnoDB;
ALTER TABLE Vegas ADD CONSTRAINT PK_Vegas PRIMARY KEY(VeId);
CREATE INDEX VeScore ON Vegas (VeScore,VeX);
CREATE TABLE F2FGrid (
	F2FTournament INT UNSIGNED NOT NULL,
	F2FPhase TINYINT UNSIGNED NOT NULL,
	F2FRound TINYINT UNSIGNED NOT NULL,
	F2FMatchNo1 TINYINT UNSIGNED NOT NULL,
	F2FMatchNo2 TINYINT UNSIGNED NOT NULL,
	F2FGroup TINYINT UNSIGNED NOT NULL
) ENGINE=InnoDB;
ALTER TABLE F2FGrid ADD CONSTRAINT PK_F2FGrid PRIMARY KEY(F2FGroup,F2FMatchNo1,F2FMatchNo2,F2FPhase,F2FRound,F2FTournament);
CREATE TABLE FinOdfTiming (
	FinOdfTournament INT NOT NULL,
	FinOdfEvent VARCHAR(4) NOT NULL,
	FinOdfTeamEvent TINYINT NOT NULL,
	FinOdfMatchno INT NOT NULL,
	FinOdfStartlist DATETIME NOT NULL,
	FinOdfPrepare DATETIME NOT NULL,
	FinOdfBegin DATETIME NOT NULL,
	FinOdfEnd DATETIME NOT NULL,
	FinOdfUnofficial DATETIME NOT NULL,
	FinOdfConfirmed DATETIME NOT NULL,
	FinOdfArrows TEXT NOT NULL,
	FinOdfTiming TEXT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE FinOdfTiming ADD CONSTRAINT PK_FinOdfTiming PRIMARY KEY(FinOdfEvent,FinOdfMatchno,FinOdfTeamEvent,FinOdfTournament);
CREATE INDEX FinOdfBegin ON FinOdfTiming (FinOdfBegin,FinOdfTournament,FinOdfTeamEvent,FinOdfEvent,FinOdfMatchno);
CREATE INDEX FinOdfConfirmed ON FinOdfTiming (FinOdfConfirmed,FinOdfTournament,FinOdfTeamEvent,FinOdfEvent,FinOdfMatchno);
CREATE INDEX FinOdfEnd ON FinOdfTiming (FinOdfEnd,FinOdfTournament,FinOdfTeamEvent,FinOdfEvent,FinOdfMatchno);
CREATE INDEX FinOdfPrepare ON FinOdfTiming (FinOdfPrepare,FinOdfTournament,FinOdfTeamEvent,FinOdfEvent,FinOdfMatchno);
CREATE INDEX FinOdfUnofficial ON FinOdfTiming (FinOdfUnofficial,FinOdfTournament,FinOdfTeamEvent,FinOdfEvent,FinOdfMatchno);
CREATE TABLE FinTrainingEvent (
	FteTournament INT UNSIGNED NOT NULL,
	FteScheduledDate DATE NOT NULL,
	FteScheduledTime TIME NOT NULL,
	FteTargetFrom VARCHAR(3) NOT NULL,
	FteEvent VARCHAR(4) NOT NULL,
	FteTeamEvent TINYINT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB;
ALTER TABLE FinTrainingEvent ADD CONSTRAINT PK_FinTrainingEvent PRIMARY KEY(FteEvent,FteScheduledDate,FteScheduledTime,FteTargetFrom,FteTeamEvent,FteTournament);
CREATE TABLE CasRankMatch (
	CRMEventPhase TINYINT NOT NULL,
	CRMRank TINYINT NOT NULL,
	CRMMatchNo TINYINT UNSIGNED NOT NULL
) ENGINE=InnoDB;
ALTER TABLE CasRankMatch ADD CONSTRAINT PK_CasRankMatch PRIMARY KEY(CRMEventPhase,CRMRank);
CREATE TABLE F2FFinal (
	F2FEnId INT UNSIGNED NOT NULL DEFAULT 0,
	F2FEvent VARCHAR(4) NOT NULL,
	F2FPhase TINYINT UNSIGNED NOT NULL,
	F2FRound TINYINT UNSIGNED NOT NULL,
	F2FGroup TINYINT UNSIGNED NOT NULL,
	F2FMatchNo TINYINT UNSIGNED NOT NULL DEFAULT 0,
	F2FTournament INT UNSIGNED NOT NULL DEFAULT 0,
	F2FTarget VARCHAR(3) NOT NULL DEFAULT '',
	F2FArrowstring VARCHAR(36) NOT NULL,
	F2FScore SMALLINT NOT NULL DEFAULT 0,
	F2FPoints TINYINT NOT NULL DEFAULT 0,
	F2FSchedule DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	F2FTimeStamp TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	F2FSetScore TINYINT NOT NULL,
	F2FEndPoints VARCHAR(36) NOT NULL,
	F2FMatchPoints VARCHAR(255) NOT NULL,
	F2FHits TINYINT NOT NULL,
	F2FTieBreak TINYINT NOT NULL,
	F2FTieArrowstring VARCHAR(3) NOT NULL,
	F2FTieScore TINYINT NOT NULL,
	F2FLive TINYINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE F2FFinal ADD CONSTRAINT PK_F2FFinal PRIMARY KEY(F2FEnId,F2FEvent,F2FGroup,F2FMatchNo,F2FPhase,F2FRound,F2FTournament);
CREATE TABLE AccOperationType (
	AOTId SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	AOTDescr VARCHAR(32) NOT NULL,
	AOTOrder TINYINT NOT NULL
) ENGINE=InnoDB;
CREATE TABLE TVContents (
	TVCId INT NOT NULL,
	TVCTournament INT NOT NULL,
	TVCName VARCHAR(50) NOT NULL,
	TVCContent MEDIUMBLOB NOT NULL,
	TVCMimeType VARCHAR(50) NOT NULL,
	TVCTime TINYINT NOT NULL,
	TVCScroll TINYINT NOT NULL,
	TVCTimestamp TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB;
ALTER TABLE TVContents ADD CONSTRAINT PK_TVContents PRIMARY KEY(TVCId,TVCTournament);
CREATE TABLE LookUpEntries (
	LueCode VARCHAR(25) NOT NULL,
	LueIocCode VARCHAR(5) NOT NULL DEFAULT '',
	LueFamilyName VARCHAR(60) NOT NULL,
	LueName VARCHAR(30) NOT NULL,
	LueSex BIT(3) NOT NULL DEFAULT 48,
	LueCtrlCode DATE DEFAULT NULL,
	LueCountry VARCHAR(10) NOT NULL,
	LueCoDescr VARCHAR(80) NOT NULL,
	LueCoShort VARCHAR(30) NOT NULL,
	LueCountry2 VARCHAR(10) NOT NULL,
	LueCoDescr2 VARCHAR(80) NOT NULL,
	LueCoShort2 VARCHAR(30) NOT NULL,
	LueCountry3 VARCHAR(10) NOT NULL,
	LueCoDescr3 VARCHAR(80) NOT NULL,
	LueCoShort3 VARCHAR(30) NOT NULL,
	LueDivision VARCHAR(2) NOT NULL,
	LueClass VARCHAR(2) NOT NULL,
	LueSubClass VARCHAR(2) NOT NULL,
	LueStatus TINYINT NOT NULL,
	LueStatusValidUntil DATE NOT NULL DEFAULT '0000-00-00',
	LueDefault TINYINT NOT NULL DEFAULT 0,
	LueNameOrder TINYINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE LookUpEntries ADD CONSTRAINT PK_LookUpEntries PRIMARY KEY(LueClass,LueCode,LueDivision,LueIocCode);
CREATE INDEX LueCode ON LookUpEntries (LueCode);
CREATE INDEX LueCountry ON LookUpEntries (LueCountry);
CREATE TABLE AccEntries (
	AEId INT UNSIGNED NOT NULL DEFAULT 0,
	AEOperation INT NOT NULL,
	AETournament INT UNSIGNED NOT NULL DEFAULT 0,
	AEWhen DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	AEFromIp INT UNSIGNED NOT NULL DEFAULT 0,
	AERapp TINYINT UNSIGNED NOT NULL DEFAULT 0,
	AEExtra VARCHAR(25) DEFAULT 'NULL'
) ENGINE=InnoDB;
ALTER TABLE AccEntries ADD CONSTRAINT PK_AccEntries PRIMARY KEY(AEId,AEOperation,AETournament);
CREATE TABLE PrintOutsRules (
	PorId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PorTournament INT UNSIGNED NOT NULL DEFAULT 0,
	PorRuleName VARCHAR(64) NOT NULL,
	PorTitle VARCHAR(50) NOT NULL,
	PorPrintOuts VARCHAR(255) NOT NULL,
	PorEventQual VARCHAR(255) NOT NULL,
	PorQualCollate VARCHAR(1) NOT NULL DEFAULT '1',
	PorEventFin VARCHAR(255) NOT NULL,
	PorFinCollate VARCHAR(1) NOT NULL DEFAULT '1',
	PorVisPar VARCHAR(1) NOT NULL,
	PorVisFin VARCHAR(1) NOT NULL,
	PorVisQual VARCHAR(1) NOT NULL
) ENGINE=InnoDB;
CREATE INDEX PorTournament ON PrintOutsRules (PorTournament);
CREATE TABLE Raspberries (
	RasDevice VARCHAR(35) NOT NULL,
	RasIp VARCHAR(15) NOT NULL,
	RasLocation VARCHAR(50) NOT NULL,
	RasUrl VARCHAR(255) NOT NULL,
	RasTourCode VARCHAR(11) NOT NULL,
	RasRot VARCHAR(36) NOT NULL,
	RasType VARCHAR(36) NOT NULL,
	RasLastseen DATETIME NOT NULL,
	RasActive TINYINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Raspberries ADD CONSTRAINT PK_Raspberries PRIMARY KEY(RasDevice);
CREATE INDEX Active ON Raspberries (RasActive,RasLastseen);
CREATE TABLE F2FEntries (
	F2FTournament INT UNSIGNED NOT NULL DEFAULT 0,
	F2FPhase TINYINT UNSIGNED NOT NULL DEFAULT 0,
	F2FMatchNo TINYINT UNSIGNED NOT NULL DEFAULT 0,
	F2FGroup TINYINT UNSIGNED NOT NULL,
	F2FEventCode VARCHAR(4) NOT NULL,
	F2FEnId INT UNSIGNED NOT NULL DEFAULT 0,
	F2FPoints INT NOT NULL DEFAULT 0,
	F2FScore INT NOT NULL DEFAULT 0,
	F2FRankGroup SMALLINT NOT NULL DEFAULT 0,
	F2FRankScore SMALLINT NOT NULL DEFAULT 0,
	F2FRankFinal SMALLINT NOT NULL DEFAULT 0,
	F2FTieArrowstring VARCHAR(3) NOT NULL DEFAULT '',
	F2FTieScore TINYINT NOT NULL DEFAULT 0,
	F2FDist2Center TINYINT NOT NULL DEFAULT 0,
	F2FTieArrowstring2 VARCHAR(3) NOT NULL DEFAULT '',
	F2FTieScore2 TINYINT NOT NULL DEFAULT 0,
	F2FDist2Center2 TINYINT NOT NULL DEFAULT 0,
	F2FHits TINYINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE F2FEntries ADD CONSTRAINT PK_F2FEntries PRIMARY KEY(F2FEnId,F2FEventCode,F2FGroup,F2FMatchNo,F2FPhase,F2FTournament);
CREATE TABLE TVParams (
	TVPId INT NOT NULL,
	TVPTournament INT NOT NULL,
	TVPTimeStop SMALLINT UNSIGNED NOT NULL,
	TVPTimeScroll SMALLINT UNSIGNED NOT NULL,
	TVPNumRows SMALLINT UNSIGNED NOT NULL,
	TVMaxPage TINYINT UNSIGNED NOT NULL,
	TVPSession TINYINT UNSIGNED NOT NULL,
	TVPViewNationName BIT(3) NOT NULL,
	TVPNameComplete BIT(3) NOT NULL,
	TVPViewTeamComponents BIT(3) NOT NULL,
	TVPEventInd VARCHAR(255) NOT NULL,
	TVPEventTeam VARCHAR(255) NOT NULL,
	TVPPhasesInd VARCHAR(255) NOT NULL,
	TVPPhasesTeam VARCHAR(255) NOT NULL,
	TVPColumns VARCHAR(255) NOT NULL,
	TVPPage VARCHAR(10) NOT NULL,
	TVPDefault VARCHAR(1) NOT NULL,
	TVP_TR_BGColor VARCHAR(7) NOT NULL,
	TVP_TRNext_BGColor VARCHAR(7) NOT NULL,
	TVP_TR_Color VARCHAR(7) NOT NULL,
	TVP_TRNext_Color VARCHAR(7) NOT NULL,
	TVP_Content_BGColor VARCHAR(7) NOT NULL,
	TVP_Page_BGColor VARCHAR(7) NOT NULL,
	TVP_TH_BGColor VARCHAR(7) NOT NULL,
	TVP_TH_Color VARCHAR(7) NOT NULL,
	TVP_THTitle_BGColor VARCHAR(7) NOT NULL,
	TVP_THTitle_Color VARCHAR(7) NOT NULL,
	TVP_Carattere SMALLINT UNSIGNED NOT NULL,
	TVPViewPartials VARCHAR(1) NOT NULL DEFAULT '1',
	TVPViewDetails VARCHAR(1) NOT NULL DEFAULT '1',
	TVPViewIdCard VARCHAR(1) NOT NULL DEFAULT '',
	TVPSettings TEXT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE TVParams ADD CONSTRAINT PK_TVParams PRIMARY KEY(TVPId,TVPTournament);
CREATE TABLE IndOldPositions (
	IopId INT UNSIGNED NOT NULL,
	IopEvent VARCHAR(4) NOT NULL,
	IopTournament INT NOT NULL,
	IopHits INT NOT NULL,
	IopRank SMALLINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE IndOldPositions ADD CONSTRAINT PK_IndOldPositions PRIMARY KEY(IopEvent,IopHits,IopId,IopTournament);
CREATE TABLE LookUpPaths (
	LupIocCode VARCHAR(5) NOT NULL,
	LupOrigin VARCHAR(3) NOT NULL,
	LupPath VARCHAR(255) NOT NULL,
	LupPhotoPath VARCHAR(255) NOT NULL,
	LupFlagsPath VARCHAR(255) NOT NULL,
	LupLastUpdate DATETIME DEFAULT NULL,
	LupRankingPath VARCHAR(255) NOT NULL,
	LupClubNamesPath VARCHAR(255) NOT NULL,
	LupRecordsPath VARCHAR(255) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE LookUpPaths ADD CONSTRAINT PK_LookUpPaths PRIMARY KEY(LupIocCode);
CREATE TABLE FinSchedule (
	FSEvent VARCHAR(4) NOT NULL,
	FSTeamEvent BIT(3) NOT NULL DEFAULT 48,
	FSMatchNo TINYINT UNSIGNED NOT NULL,
	FSTournament INT UNSIGNED NOT NULL,
	FSTarget VARCHAR(3) NOT NULL,
	FSGroup INT UNSIGNED NOT NULL DEFAULT 0,
	FSScheduledDate DATE NOT NULL,
	FSScheduledTime TIME DEFAULT NULL,
	FSScheduledLen SMALLINT NOT NULL DEFAULT 0,
	FSLetter VARCHAR(5) NOT NULL,
	FsShift INT DEFAULT NULL,
	FSTimestamp TIMESTAMP NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB;
ALTER TABLE FinSchedule ADD CONSTRAINT PK_FinSchedule PRIMARY KEY(FSEvent,FSMatchNo,FSTeamEvent,FSTournament);
CREATE UNIQUE INDEX FSTournament ON FinSchedule (FSTournament,FSTeamEvent,FSEvent,FSMatchNo,FSScheduledDate,FSScheduledTime);
CREATE TABLE TargetFaces (
	TfId INT NOT NULL,
	TfName VARCHAR(50) NOT NULL,
	TfTournament INT NOT NULL,
	TfClasses VARCHAR(4) NOT NULL,
	TfRegExp VARCHAR(255) NOT NULL,
	TfGolds VARCHAR(5) NOT NULL,
	TfXNine VARCHAR(5) NOT NULL,
	TfGoldsChars VARCHAR(16) NOT NULL,
	TfXNineChars VARCHAR(16) NOT NULL,
	TfT1 INT NOT NULL,
	TfW1 INT NOT NULL,
	TfT2 INT NOT NULL,
	TfW2 INT NOT NULL,
	TfT3 INT NOT NULL,
	TfW3 INT NOT NULL,
	TfT4 INT NOT NULL,
	TfW4 INT NOT NULL,
	TfT5 INT NOT NULL,
	TfW5 INT NOT NULL,
	TfT6 INT NOT NULL,
	TfW6 INT NOT NULL,
	TfT7 INT NOT NULL,
	TfW7 INT NOT NULL,
	TfT8 INT NOT NULL,
	TfW8 INT NOT NULL,
	TfDefault VARCHAR(1) NOT NULL DEFAULT '',
	TfTourRules VARCHAR(75) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE TargetFaces ADD CONSTRAINT PK_TargetFaces PRIMARY KEY(TfId,TfTournament);
CREATE TABLE TourRecords (
	TrTournament INT NOT NULL,
	TrRecType VARCHAR(2) NOT NULL,
	TrRecCode VARCHAR(25) NOT NULL,
	TrRecTeam SMALLINT NOT NULL,
	TrRecPara VARCHAR(1) NOT NULL,
	TrColor VARCHAR(6) NOT NULL DEFAULT '000000',
	TrFlags SET('bar','gap') NOT NULL
) ENGINE=InnoDB;
ALTER TABLE TourRecords ADD CONSTRAINT PK_TourRecords PRIMARY KEY(TrRecCode,TrRecPara,TrRecTeam,TrRecType,TrTournament);
CREATE TABLE AccColors (
	AcTournament INT UNSIGNED NOT NULL,
	AcDivClass VARCHAR(4) NOT NULL,
	AcColor VARCHAR(6) NOT NULL,
	AcIsAthlete TINYINT UNSIGNED NOT NULL,
	AcTitleReverse TINYINT NOT NULL DEFAULT 0,
	AcArea0 TINYINT NOT NULL DEFAULT 0,
	AcArea1 TINYINT NOT NULL DEFAULT 0,
	AcArea2 TINYINT NOT NULL DEFAULT 0,
	AcArea3 TINYINT NOT NULL DEFAULT 0,
	AcArea4 TINYINT NOT NULL DEFAULT 0,
	AcArea5 TINYINT NOT NULL DEFAULT 0,
	AcArea6 TINYINT NOT NULL DEFAULT 0,
	AcArea7 TINYINT NOT NULL DEFAULT 0,
	AcAreaStar TINYINT NOT NULL DEFAULT 0,
	AcTransport TINYINT NOT NULL DEFAULT 0,
	AcAccomodation TINYINT NOT NULL DEFAULT 0,
	AcMeal TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB;
ALTER TABLE AccColors ADD CONSTRAINT PK_AccColors PRIMARY KEY(AcDivClass,AcTournament);
CREATE TABLE CasTeam (
	CaTournament INT UNSIGNED NOT NULL DEFAULT 0,
	CaPhase TINYINT UNSIGNED NOT NULL DEFAULT 0,
	CaMatchNo TINYINT UNSIGNED NOT NULL DEFAULT 0,
	CaEventCode VARCHAR(4) NOT NULL,
	CaTeam INT UNSIGNED NOT NULL DEFAULT 0,
	CaSubTeam TINYINT NOT NULL,
	CaRank TINYINT UNSIGNED NOT NULL,
	CaTiebreak VARCHAR(9) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE CasTeam ADD CONSTRAINT PK_CasTeam PRIMARY KEY(CaEventCode,CaMatchNo,CaPhase,CaSubTeam,CaTeam,CaTournament);
CREATE TABLE Awarded (
	AwEntry INT NOT NULL,
	AwTournament INT NOT NULL,
	AwDivision VARCHAR(2) NOT NULL,
	AwClass VARCHAR(2) NOT NULL,
	AwSubClass VARCHAR(2) NOT NULL,
	AwRank INT NOT NULL,
	AwValue DECIMAL(12, 2) NOT NULL,
	AwPrinted VARCHAR(1) NOT NULL,
	AwMailed VARCHAR(1) NOT NULL,
	AwReference VARCHAR(25) NOT NULL,
	AwExtra TEXT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Awarded ADD CONSTRAINT PK_Awarded PRIMARY KEY(AwEntry);
CREATE TABLE TournamentDistances (
	TdClasses VARCHAR(4) NOT NULL,
	TdType SMALLINT UNSIGNED NOT NULL,
	TdTournament INT NOT NULL,
	Td1 VARCHAR(10) NOT NULL,
	Td2 VARCHAR(10) NOT NULL,
	Td3 VARCHAR(10) NOT NULL,
	Td4 VARCHAR(10) NOT NULL,
	Td5 VARCHAR(10) NOT NULL,
	Td6 VARCHAR(10) NOT NULL,
	Td7 VARCHAR(10) NOT NULL,
	Td8 VARCHAR(10) NOT NULL,
	TdTourRules VARCHAR(75) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE TournamentDistances ADD CONSTRAINT PK_TournamentDistances PRIMARY KEY(TdClasses,TdTournament,TdType);
CREATE TABLE ModulesParameters (
	MpModule VARCHAR(50) NOT NULL,
	MpParameter VARCHAR(30) NOT NULL,
	MpTournament INT UNSIGNED NOT NULL,
	MpValue TEXT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE ModulesParameters ADD CONSTRAINT PK_ModulesParameters PRIMARY KEY(MpModule,MpParameter,MpTournament);
CREATE TABLE Grids (
	GrMatchNo TINYINT UNSIGNED NOT NULL DEFAULT 0,
	GrPosition SMALLINT NOT NULL DEFAULT 0,
	GrPosition2 SMALLINT NOT NULL DEFAULT 0,
	GrPhase TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB;
ALTER TABLE Grids ADD CONSTRAINT PK_Grids PRIMARY KEY(GrMatchNo);
CREATE INDEX GrPosition ON Grids (GrPosition,GrPhase);
CREATE INDEX GrPosition2 ON Grids (GrPosition2,GrPhase);
CREATE TABLE TVSequence (
	TVSId INT NOT NULL,
	TVSTournament INT NOT NULL,
	TVSRule INT NOT NULL,
	TVSContent INT NOT NULL,
	TVSCntSameTour TINYINT NOT NULL,
	TVSTime TINYINT NOT NULL,
	TVSScroll TINYINT NOT NULL,
	TVSTable VARCHAR(5) NOT NULL,
	TVSOrder TINYINT NOT NULL,
	TVSFullScreen VARCHAR(1) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE TVSequence ADD CONSTRAINT PK_TVSequence PRIMARY KEY(TVSId,TVSTournament);
CREATE TABLE PrintOuts (
	PoCode VARCHAR(25) NOT NULL,
	PoType VARCHAR(1) NOT NULL,
	PoFile VARCHAR(255) NOT NULL,
	PoFunction VARCHAR(20) NOT NULL,
	PoTeam VARCHAR(1) NOT NULL,
	PoOrdine INT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE PrintOuts ADD CONSTRAINT PK_PrintOuts PRIMARY KEY(PoCode);
CREATE TABLE TargetGroups (
	TgTournament INT NOT NULL,
	TgSession VARCHAR(1) NOT NULL,
	TgTargetNo VARCHAR(4) NOT NULL,
	TgGroup VARCHAR(25) NOT NULL,
	TgSesType VARCHAR(2) NOT NULL DEFAULT 'Q'
) ENGINE=InnoDB;
ALTER TABLE TargetGroups ADD CONSTRAINT PK_TargetGroups PRIMARY KEY(TgSession,TgSesType,TgTargetNo,TgTournament);
CREATE INDEX TgTournament ON TargetGroups (TgTournament,TgGroup,TgTargetNo);
CREATE TABLE HhtData (
	HdTournament INT NOT NULL,
	HdTargetNo VARCHAR(5) NOT NULL,
	HdDistance TINYINT NOT NULL,
	HdFinScheduling DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	HdTeamEvent BIT(3) NOT NULL DEFAULT 48,
	HdArrowStart TINYINT NOT NULL,
	HdArrowEnd TINYINT NOT NULL,
	HdArrowString VARCHAR(6) NOT NULL,
	HdEnId INT UNSIGNED NOT NULL,
	HdMatchNo TINYINT UNSIGNED DEFAULT NULL,
	HdEvent VARCHAR(4) NOT NULL DEFAULT '',
	HdHhtId INT NOT NULL,
	HdRealTargetNo VARCHAR(3) NOT NULL,
	HdLetter VARCHAR(1) NOT NULL,
	HdTimeStamp DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB;
ALTER TABLE HhtData ADD CONSTRAINT PK_HhtData PRIMARY KEY(HdArrowStart,HdDistance,HdFinScheduling,HdTargetNo,HdTeamEvent,HdTournament);
CREATE INDEX HdTournament ON HhtData (HdTournament,HdTeamEvent,HdHhtId,HdFinScheduling,HdTargetNo);
CREATE INDEX HdTournament_2 ON HhtData (HdTournament,HdTimeStamp,HdDistance,HdArrowStart);
CREATE TABLE Parameters (
	ParId VARCHAR(15) NOT NULL,
	ParValue VARCHAR(255) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Parameters ADD CONSTRAINT PK_Parameters PRIMARY KEY(ParId);
CREATE TABLE AccPrice (
	APId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	APTournament INT UNSIGNED NOT NULL DEFAULT 0,
	APDivClass VARCHAR(4) NOT NULL,
	APPrice FLOAT(15, 2) NOT NULL DEFAULT 0.00
) ENGINE=InnoDB;
CREATE UNIQUE INDEX APTournament ON AccPrice (APTournament,APDivClass);
CREATE TABLE Teams (
	TeCoId INT NOT NULL,
	TeSubTeam TINYINT NOT NULL,
	TeEvent VARCHAR(4) NOT NULL,
	TeTournament INT NOT NULL,
	TeFinEvent TINYINT UNSIGNED NOT NULL DEFAULT 0,
	TeScore SMALLINT NOT NULL,
	TeHits SMALLINT NOT NULL,
	TeGold SMALLINT NOT NULL,
	TeXnine SMALLINT NOT NULL,
	TeTie BIT(3) NOT NULL,
	TeTieBreak VARCHAR(15) NOT NULL,
	TeRank TINYINT NOT NULL,
	TeHitsCalcOld SMALLINT NOT NULL,
	TeRankFinal SMALLINT NOT NULL,
	TeSO SMALLINT NOT NULL DEFAULT 0,
	TeTimeStamp TIMESTAMP DEFAULT NULL,
	TeTimeStampFinal DATETIME DEFAULT NULL,
	TeFinal TINYINT UNSIGNED NOT NULL DEFAULT 0,
	TeBacknoPrinted DATETIME NOT NULL,
	TeNotes VARCHAR(30) NOT NULL
) ENGINE=InnoDB;
ALTER TABLE Teams ADD CONSTRAINT PK_Teams PRIMARY KEY(TeCoId,TeEvent,TeFinEvent,TeSubTeam,TeTournament);
CREATE INDEX TeTournament ON Teams (TeTournament,TeFinEvent,TeEvent,TeScore);
CREATE INDEX TeTournament_2 ON Teams (TeTournament,TeSO,TeEvent);
CREATE INDEX TeTournament_3 ON Teams (TeTournament,TeEvent,TeFinEvent,TeScore);
CREATE INDEX TeTournament_4 ON Teams (TeTournament,TeFinEvent,TeEvent,TeSO);
CREATE TABLE TeamFinComponent (
	TfcCoId INT NOT NULL,
	TfcSubTeam TINYINT NOT NULL,
	TfcTournament INT NOT NULL,
	TfcEvent VARCHAR(4) NOT NULL,
	TfcId INT UNSIGNED NOT NULL,
	TfcOrder TINYINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE TeamFinComponent ADD CONSTRAINT PK_TeamFinComponent PRIMARY KEY(TfcCoId,TfcEvent,TfcId,TfcSubTeam,TfcTournament);
CREATE TABLE ClubTeam (
	CTTournament INT UNSIGNED NOT NULL DEFAULT 0,
	CTPhase TINYINT UNSIGNED NOT NULL DEFAULT 0,
	CTMatchNo TINYINT UNSIGNED NOT NULL DEFAULT 0,
	CTEventCode VARCHAR(4) NOT NULL,
	CTPrimary TINYINT UNSIGNED NOT NULL,
	CTTeam INT UNSIGNED NOT NULL DEFAULT 0,
	CTSubTeam TINYINT NOT NULL,
	CTBonus TINYINT UNSIGNED NOT NULL DEFAULT 0,
	CTRank TINYINT UNSIGNED NOT NULL,
	CTTiebreak VARCHAR(9) NOT NULL DEFAULT '',
	CTSchedule DATETIME NOT NULL,
	CTQualRank INT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE ClubTeam ADD CONSTRAINT PK_ClubTeam PRIMARY KEY(CTEventCode,CTMatchNo,CTPhase,CTPrimary,CTSubTeam,CTTeam,CTTournament);
CREATE TABLE QualOldPositions (
	QopId INT UNSIGNED NOT NULL,
	QopHits INT NOT NULL,
	QopClRank SMALLINT NOT NULL,
	QopSubClassRank SMALLINT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE QualOldPositions ADD CONSTRAINT PK_QualOldPositions PRIMARY KEY(QopHits,QopId);
CREATE VIEW EventCategories AS select `ianseodb_dev`.`EventClass`.`EcCode` AS `EcCode`,`ianseodb_dev`.`EventClass`.`EcTeamEvent` AS `EcTeamEvent`,`ianseodb_dev`.`EventClass`.`EcTournament` AS `EcTournament`,`ianseodb_dev`.`EventClass`.`EcClass` AS `EcClass`,`ianseodb_dev`.`EventClass`.`EcDivision` AS `EcDivision`,`ianseodb_dev`.`EventClass`.`EcNumber` AS `EcNumber`,`ianseodb_dev`.`EventClass`.`EcTourRules` AS `EcTourRules`,`ianseodb_dev`.`Events`.`EvCode` AS `EvCode`,`ianseodb_dev`.`Events`.`EvTeamEvent` AS `EvTeamEvent`,`ianseodb_dev`.`Events`.`EvTournament` AS `EvTournament`,`ianseodb_dev`.`Events`.`EvEventName` AS `EvEventName`,`ianseodb_dev`.`Events`.`EvProgr` AS `EvProgr`,`ianseodb_dev`.`Events`.`EvShootOff` AS `EvShootOff`,`ianseodb_dev`.`Events`.`EvE1ShootOff` AS `EvE1ShootOff`,`ianseodb_dev`.`Events`.`EvE2ShootOff` AS `EvE2ShootOff`,`ianseodb_dev`.`Events`.`EvSession` AS `EvSession`,`ianseodb_dev`.`Events`.`EvPrint` AS `EvPrint`,`ianseodb_dev`.`Events`.`EvQualPrintHead` AS `EvQualPrintHead`,`ianseodb_dev`.`Events`.`EvQualLastUpdate` AS `EvQualLastUpdate`,`ianseodb_dev`.`Events`.`EvFinalFirstPhase` AS `EvFinalFirstPhase`,`ianseodb_dev`.`Events`.`EvFinalPrintHead` AS `EvFinalPrintHead`,`ianseodb_dev`.`Events`.`EvFinalLastUpdate` AS `EvFinalLastUpdate`,`ianseodb_dev`.`Events`.`EvFinalTargetType` AS `EvFinalTargetType`,`ianseodb_dev`.`Events`.`EvTargetSize` AS `EvTargetSize`,`ianseodb_dev`.`Events`.`EvDistance` AS `EvDistance`,`ianseodb_dev`.`Events`.`EvFinalAthTarget` AS `EvFinalAthTarget`,`ianseodb_dev`.`Events`.`EvElim1` AS `EvElim1`,`ianseodb_dev`.`Events`.`EvElim2` AS `EvElim2`,`ianseodb_dev`.`Events`.`EvPartialTeam` AS `EvPartialTeam`,`ianseodb_dev`.`Events`.`EvMultiTeam` AS `EvMultiTeam`,`ianseodb_dev`.`Events`.`EvMixedTeam` AS `EvMixedTeam`,`ianseodb_dev`.`Events`.`EvTeamCreationMode` AS `EvTeamCreationMode`,`ianseodb_dev`.`Events`.`EvMaxTeamPerson` AS `EvMaxTeamPerson`,`ianseodb_dev`.`Events`.`EvRunning` AS `EvRunning`,`ianseodb_dev`.`Events`.`EvMatchMode` AS `EvMatchMode`,`ianseodb_dev`.`Events`.`EvMatchArrowsNo` AS `EvMatchArrowsNo`,`ianseodb_dev`.`Events`.`EvElimEnds` AS `EvElimEnds`,`ianseodb_dev`.`Events`.`EvElimArrows` AS `EvElimArrows`,`ianseodb_dev`.`Events`.`EvElimSO` AS `EvElimSO`,`ianseodb_dev`.`Events`.`EvFinEnds` AS `EvFinEnds`,`ianseodb_dev`.`Events`.`EvFinArrows` AS `EvFinArrows`,`ianseodb_dev`.`Events`.`EvFinSO` AS `EvFinSO`,`ianseodb_dev`.`Events`.`EvRecCategory` AS `EvRecCategory`,`ianseodb_dev`.`Events`.`EvWaCategory` AS `EvWaCategory`,`ianseodb_dev`.`Events`.`EvMedals` AS `EvMedals`,`ianseodb_dev`.`Events`.`EvTourRules` AS `EvTourRules` from (`ianseodb_dev`.`EventClass` join `ianseodb_dev`.`Events` on(`ianseodb_dev`.`Events`.`EvCode` = `ianseodb_dev`.`EventClass`.`EcCode` and `ianseodb_dev`.`Events`.`EvTeamEvent` = `ianseodb_dev`.`EventClass`.`EcTeamEvent` and `ianseodb_dev`.`Events`.`EvTournament` = `ianseodb_dev`.`EventClass`.`EcTournament`));
CREATE TABLE Reviews (
	RevEvent VARCHAR(4) NOT NULL,
	RevMatchNo TINYINT UNSIGNED NOT NULL,
	RevTournament INT UNSIGNED NOT NULL,
	RevTeamEvent TINYINT NOT NULL,
	RevLanguage1 TEXT NOT NULL,
	RevLanguage2 TEXT NOT NULL,
	RevDateTime DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	RevSyncro DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB;
ALTER TABLE Reviews ADD CONSTRAINT PK_Reviews PRIMARY KEY(RevEvent,RevMatchNo,RevTeamEvent,RevTournament);
CREATE TABLE IskDevices (
	IskDvTournament INT NOT NULL,
	IskDvDevice VARCHAR(36) NOT NULL,
	IskDvGroup TINYINT NOT NULL,
	IskDvSchedKey VARCHAR(25) NOT NULL,
	IskDvVersion VARCHAR(12) DEFAULT 'NULL',
	IskDvAppVersion TINYINT NOT NULL,
	IskDvCode VARCHAR(2) NOT NULL,
	IskDvTarget VARCHAR(3) NOT NULL,
	IskDvTargetReq VARCHAR(3) NOT NULL,
	IskDvState TINYINT NOT NULL,
	IskDvBattery TINYINT NOT NULL,
	IskDvIpAddress VARCHAR(15) NOT NULL,
	IskDvLastSeen DATETIME NOT NULL,
	IskDvAuthRequest TINYINT NOT NULL,
	IskDvProActive TINYINT NOT NULL,
	IskDvProConnected TINYINT NOT NULL,
	IskDvSetup BLOB NOT NULL,
	IskDvRunningConf TEXT NOT NULL,
	IskDvUrlDownload TINYTEXT NOT NULL,
	IskDvGps TEXT NOT NULL
) ENGINE=InnoDB;
ALTER TABLE IskDevices ADD CONSTRAINT PK_IskDevices PRIMARY KEY(IskDvDevice);
CREATE INDEX IskDvTournament ON IskDevices (IskDvTournament);
CREATE INDEX IskDvTournament_2 ON IskDevices (IskDvTournament,IskDvGroup);
CREATE INDEX IskDvTournament_3 ON IskDevices (IskDvTournament,IskDvSchedKey,IskDvGroup);
CREATE TABLE ClubTeamGroupMatch (
	CTGMGroup TINYINT UNSIGNED NOT NULL,
	CTGMMatchNo TINYINT UNSIGNED NOT NULL
) ENGINE=InnoDB;
ALTER TABLE ClubTeamGroupMatch ADD CONSTRAINT PK_ClubTeamGroupMatch PRIMARY KEY(CTGMGroup,CTGMMatchNo);
CREATE TABLE VegasAwards (
	VaTournament INT NOT NULL,
	VaDivision VARCHAR(2) NOT NULL,
	VaClass VARCHAR(2) NOT NULL,
	VaSubClass VARCHAR(2) NOT NULL,
	VaRank INT NOT NULL,
	VaAward FLOAT(15, 2) NOT NULL DEFAULT 0.00,
	VaToDelete TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB;
ALTER TABLE VegasAwards ADD CONSTRAINT PK_VegasAwards PRIMARY KEY(VaClass,VaDivision,VaRank,VaSubClass,VaTournament);
